-- LGDXMEMBER TABLE 생성
-- COLUMN
-- ID 문자(50) PRIMARY KEY
-- PW 문자(50) NOT NULL
-- NAME 문자(50) NOT NULL
-- AGE 숫자
-- SCORE 숫자

CREATE TABLE LGDXMEMBER (
    ID VARCHAR2(50),
    PW VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    AGE NUMBER,
    SCORE NUMBER
);
ALTER TABLE LGDXMEMBER ADD CONSTRAINT ID PRIMARY KEY(ID);

COMMIT;

SELECT * FROM LGDXMEMBER;

INSERT INTO LGDXMEMBER VALUES('lgdx', '12345', '이도연', 20, 80);